from .anasayfa import anasayfa
from .detay import DetayView
from .iletisim import iletisim
from .kategori import KategoriListView
from .yazilarim import yazilarim
from .yazi_ekle import yazi_ekle
from .yazi_guncelle import yazi_guncelle
from .yazi_sil import YaziSilDeleteView
from .yorum_sil import yorum_sil